param([switch]$Background)
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference='Stop'; $AgentVersion='1.3.0'; $ApiBase='https://billing.solarnetportal.com/api/v1'
$DataDir=Join-Path $env:LOCALAPPDATA 'SolarNetDeviceAgent'; $IdentityFile=Join-Path $DataDir 'installation-id.txt'; $TokenFile=Join-Path $DataDir 'device-token.dat'
New-Item -ItemType Directory -Path $DataDir -Force|Out-Null
if(-not(Test-Path $IdentityFile)){[guid]::NewGuid().ToString()|Set-Content $IdentityFile -Encoding ASCII}
function Save-Token([string]$value){ConvertTo-SecureString $value -AsPlainText -Force|ConvertFrom-SecureString|Set-Content $TokenFile -Encoding ASCII}
function Read-Token{if(-not(Test-Path $TokenFile)){return $null};$s=Get-Content $TokenFile|ConvertTo-SecureString;$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function Enable-Autostart{$command='powershell.exe -NoLogo -NoProfile -WindowStyle Hidden -STA -ExecutionPolicy Bypass -File "'+$PSCommandPath+'" -Background';New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'SolarNetDeviceAgent' -Value $command -PropertyType String -Force|Out-Null}
function Get-SecurityPosture{
 $result=[ordered]@{firewall_enabled=$null;defender_enabled=$null;realtime_protection_enabled=$null;bitlocker_enabled=$null;secure_boot_enabled=$null;pending_reboot=$false;antivirus_signature_updated_at=$null}
 try{$profiles=@(Get-NetFirewallProfile -ErrorAction Stop);$result.firewall_enabled=($profiles.Count -gt 0 -and @($profiles|Where-Object{-not $_.Enabled}).Count -eq 0)}catch{}
 try{$mp=Get-MpComputerStatus -ErrorAction Stop;$result.defender_enabled=[bool]$mp.AntivirusEnabled;$result.realtime_protection_enabled=[bool]$mp.RealTimeProtectionEnabled;if($mp.AntivirusSignatureLastUpdated){$result.antivirus_signature_updated_at=$mp.AntivirusSignatureLastUpdated.ToUniversalTime().ToString('o')}}catch{}
 try{$volume=Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction Stop;$result.bitlocker_enabled=($volume.ProtectionStatus -eq 'On')}catch{}
 try{$result.secure_boot_enabled=[bool](Confirm-SecureBootUEFI -ErrorAction Stop)}catch{}
 try{$result.pending_reboot=(Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired')}catch{}
 return $result
}
function Invoke-Api($path,$body,$token=''){$headers=@{Accept='application/json'};if($token){$headers.Authorization="Bearer $token"};Invoke-RestMethod -Method Post -Uri "$ApiBase/$path" -Headers $headers -ContentType 'application/json' -Body($body|ConvertTo-Json -Depth 4)-TimeoutSec 15}
function Send-CommandResult($token,$commandId,$result,$message){Invoke-Api 'employee-device-agent/command-result' @{command_id=$commandId;status=$result;result_message=$message} $token|Out-Null}
function Invoke-DeviceCommand($token,$command){
 try{$reason=if([string]::IsNullOrWhiteSpace([string]$command.reason)){'No reason supplied'}else{[string]$command.reason}
  if($command.command -eq 'message'){[Windows.Forms.MessageBox]::Show("$($command.message)`r`n`r`nReason: $reason",'SolarNet administrator message',[Windows.Forms.MessageBoxButtons]::OK,[Windows.Forms.MessageBoxIcon]::Information)|Out-Null;Send-CommandResult $token $command.id 'completed' 'Message displayed and acknowledged.';return}
  if($command.command -eq 'lock'){$answer=[Windows.Forms.MessageBox]::Show("A SolarNet administrator requests that this computer be locked.`r`n`r`nReason: $reason`r`n`r`nLock now?",'SolarNet device action request',[Windows.Forms.MessageBoxButtons]::YesNo,[Windows.Forms.MessageBoxIcon]::Question);if($answer -ne [Windows.Forms.DialogResult]::Yes){Send-CommandResult $token $command.id 'declined' 'Employee declined the lock request.';return};Start-Process -FilePath 'rundll32.exe' -ArgumentList 'user32.dll,LockWorkStation' -WindowStyle Hidden;Send-CommandResult $token $command.id 'completed' 'Employee approved; workstation lock was requested.';return}
  if($command.command -eq 'restart'){$answer=[Windows.Forms.MessageBox]::Show("A SolarNet administrator requests a Windows restart in 60 seconds.`r`n`r`nReason: $reason`r`n`r`nApprove restart?",'SolarNet device action request',[Windows.Forms.MessageBoxButtons]::YesNo,[Windows.Forms.MessageBoxIcon]::Warning);if($answer -ne [Windows.Forms.DialogResult]::Yes){Send-CommandResult $token $command.id 'declined' 'Employee declined the restart request.';return};Start-Process -FilePath 'shutdown.exe' -ArgumentList '/r','/t','60','/c','SolarNet approved support restart' -WindowStyle Hidden;Send-CommandResult $token $command.id 'completed' 'Employee approved; restart scheduled in 60 seconds.';return}
  Send-CommandResult $token $command.id 'failed' 'Unsupported command received.'
 }catch{try{Send-CommandResult $token $command.id 'failed' $_.Exception.Message}catch{}}
}
$form=New-Object Windows.Forms.Form;$form.Text='SolarNet Employee Device Agent';$form.Size=New-Object Drawing.Size(520,510);$form.StartPosition='CenterScreen';$form.BackColor=[Drawing.Color]::FromArgb(5,15,32);$form.ForeColor=[Drawing.Color]::White;$form.Font=New-Object Drawing.Font('Segoe UI',10);$form.FormBorderStyle='FixedDialog';$form.MaximizeBox=$false
$allowExit=$false;$tray=New-Object Windows.Forms.NotifyIcon;$tray.Icon=[Drawing.SystemIcons]::Shield;$tray.Text='SolarNet Employee Device Agent';$tray.Visible=$true
$trayMenu=New-Object Windows.Forms.ContextMenuStrip;$openItem=$trayMenu.Items.Add('Open SolarNet Agent');$exitItem=$trayMenu.Items.Add('Exit SolarNet Agent');$tray.ContextMenuStrip=$trayMenu
$openAgent={$form.Show();$form.WindowState='Normal';$form.Activate()};$openItem.Add_Click($openAgent);$tray.Add_DoubleClick($openAgent)
$exitItem.Add_Click({$script:allowExit=$true;$timer.Stop();$tray.Visible=$false;$form.Close()})
$form.Add_FormClosing({param($sender,$eventArgs);if(-not $script:allowExit){$eventArgs.Cancel=$true;$form.Hide();$tray.ShowBalloonTip(2500,'SolarNet Agent','Still running in the notification area and sending secure heartbeats.',[Windows.Forms.ToolTipIcon]::Info)}})
function Label($text,$x,$y,$w=450,$h=24,$bold=$false){$v=New-Object Windows.Forms.Label;$v.Text=$text;$v.Location=New-Object Drawing.Point($x,$y);$v.Size=New-Object Drawing.Size($w,$h);if($bold){$v.Font=New-Object Drawing.Font('Segoe UI',11,[Drawing.FontStyle]::Bold)};$form.Controls.Add($v);$v}
Label 'SOLARNET EMPLOYEE DEVICE AGENT' 28 24 450 30 $true|Out-Null;Label 'Optional heartbeat agent for selected company devices' 28 55|Out-Null;Label 'Employee name' 28 98|Out-Null
$employee=New-Object Windows.Forms.TextBox;$employee.Location=New-Object Drawing.Point(28,124);$employee.Size=New-Object Drawing.Size(445,28);$form.Controls.Add($employee)
Label 'One-time enrollment code' 28 165|Out-Null;$code=New-Object Windows.Forms.TextBox;$code.Location=New-Object Drawing.Point(28,191);$code.Size=New-Object Drawing.Size(445,28);$code.CharacterCasing='Upper';$form.Controls.Add($code)
$consent=New-Object Windows.Forms.CheckBox;$consent.Location=New-Object Drawing.Point(28,237);$consent.Size=New-Object Drawing.Size(445,55);$consent.Text='I understand this app sends device name, Windows version, agent version, online heartbeat, and a random installation ID to SolarNet.';$form.Controls.Add($consent)
$enroll=New-Object Windows.Forms.Button;$enroll.Text='Enroll this device';$enroll.Location=New-Object Drawing.Point(28,307);$enroll.Size=New-Object Drawing.Size(445,40);$enroll.BackColor=[Drawing.Color]::FromArgb(24,169,153);$enroll.FlatStyle='Flat';$form.Controls.Add($enroll)
$status=Label 'Status: Not enrolled' 28 369 445 28 $true;Label 'The application stays visible. No screen, file, keyboard, camera, microphone, or location data is collected.' 28 404 445 50|Out-Null
$timer=New-Object Windows.Forms.Timer;$timer.Interval=60000
$postureCache=$null;$lastPostureAt=[datetime]::MinValue
$heartbeat={ $token=Read-Token;if(-not $token){$status.Text='Status: Not enrolled';return};try{if(-not $script:postureCache -or ((Get-Date)-$script:lastPostureAt).TotalMinutes -ge 5){$script:postureCache=Get-SecurityPosture;$script:lastPostureAt=Get-Date};$response=Invoke-Api 'employee-device-agent/heartbeat' @{agent_version=$AgentVersion;os_version=[Environment]::OSVersion.VersionString;security_posture=$script:postureCache} $token;foreach($command in @($response.data.commands)){Invoke-DeviceCommand $token $command};$status.Text="Status: Online - heartbeat $(Get-Date -Format 'h:mm:ss tt')";$status.ForeColor=[Drawing.Color]::LightGreen}catch{$status.Text='Status: Server connection needs attention';$status.ForeColor=[Drawing.Color]::Orange}}
$timer.Add_Tick($heartbeat)
$enroll.Add_Click({if(-not $consent.Checked){[Windows.Forms.MessageBox]::Show('Review and accept the disclosed heartbeat data first.','Consent required')|Out-Null;return};if([string]::IsNullOrWhiteSpace($employee.Text)-or[string]::IsNullOrWhiteSpace($code.Text)){[Windows.Forms.MessageBox]::Show('Enter the employee name and one-time code.','Missing information')|Out-Null;return};$enroll.Enabled=$false;$status.Text='Status: Enrolling...';try{$r=Invoke-Api 'employee-device-agent/enroll' @{code=$code.Text.Trim();name=$env:COMPUTERNAME;employee_name=$employee.Text.Trim();platform='windows';os_version=[Environment]::OSVersion.VersionString;agent_version=$AgentVersion;device_fingerprint=(Get-Content $IdentityFile -Raw).Trim();consent_accepted=$true;consent_accepted_at=(Get-Date).ToUniversalTime().ToString('o')};Save-Token $r.data.device_token;Enable-Autostart;$code.Clear();$employee.Enabled=$false;$consent.Enabled=$false;$enroll.Text='Enrolled';&$heartbeat;$timer.Start()}catch{$status.Text='Status: Enrollment failed';[Windows.Forms.MessageBox]::Show($_.Exception.Message,'Enrollment failed')|Out-Null;$enroll.Enabled=$true}})
if(Read-Token){Enable-Autostart;$employee.Enabled=$false;$code.Enabled=$false;$consent.Checked=$true;$consent.Enabled=$false;$enroll.Text='Enrolled';$enroll.Enabled=$false;&$heartbeat;$timer.Start()}
if($Background){$form.Add_Shown({$form.Hide();$tray.ShowBalloonTip(2000,'SolarNet Agent','Background heartbeat is active.',[Windows.Forms.ToolTipIcon]::Info)})}
[void]$form.ShowDialog();$tray.Dispose()
