Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference='Stop'; $AgentVersion='1.0.0'; $ApiBase='https://billing.solarnetportal.com/api/v1'
$DataDir=Join-Path $env:LOCALAPPDATA 'SolarNetDeviceAgent'; $IdentityFile=Join-Path $DataDir 'installation-id.txt'; $TokenFile=Join-Path $DataDir 'device-token.dat'
New-Item -ItemType Directory -Path $DataDir -Force|Out-Null
if(-not(Test-Path $IdentityFile)){[guid]::NewGuid().ToString()|Set-Content $IdentityFile -Encoding ASCII}
function Save-Token([string]$value){ConvertTo-SecureString $value -AsPlainText -Force|ConvertFrom-SecureString|Set-Content $TokenFile -Encoding ASCII}
function Read-Token{if(-not(Test-Path $TokenFile)){return $null};$s=Get-Content $TokenFile|ConvertTo-SecureString;$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function Invoke-Api($path,$body,$token=''){$headers=@{Accept='application/json'};if($token){$headers.Authorization="Bearer $token"};Invoke-RestMethod -Method Post -Uri "$ApiBase/$path" -Headers $headers -ContentType 'application/json' -Body($body|ConvertTo-Json -Depth 4)-TimeoutSec 15}
$form=New-Object Windows.Forms.Form;$form.Text='SolarNet Employee Device Agent';$form.Size=New-Object Drawing.Size(520,510);$form.StartPosition='CenterScreen';$form.BackColor=[Drawing.Color]::FromArgb(5,15,32);$form.ForeColor=[Drawing.Color]::White;$form.Font=New-Object Drawing.Font('Segoe UI',10);$form.FormBorderStyle='FixedDialog';$form.MaximizeBox=$false
function Label($text,$x,$y,$w=450,$h=24,$bold=$false){$v=New-Object Windows.Forms.Label;$v.Text=$text;$v.Location=New-Object Drawing.Point($x,$y);$v.Size=New-Object Drawing.Size($w,$h);if($bold){$v.Font=New-Object Drawing.Font('Segoe UI',11,[Drawing.FontStyle]::Bold)};$form.Controls.Add($v);$v}
Label 'SOLARNET EMPLOYEE DEVICE AGENT' 28 24 450 30 $true|Out-Null;Label 'Optional heartbeat agent for selected company devices' 28 55|Out-Null;Label 'Employee name' 28 98|Out-Null
$employee=New-Object Windows.Forms.TextBox;$employee.Location=New-Object Drawing.Point(28,124);$employee.Size=New-Object Drawing.Size(445,28);$form.Controls.Add($employee)
Label 'One-time enrollment code' 28 165|Out-Null;$code=New-Object Windows.Forms.TextBox;$code.Location=New-Object Drawing.Point(28,191);$code.Size=New-Object Drawing.Size(445,28);$code.CharacterCasing='Upper';$form.Controls.Add($code)
$consent=New-Object Windows.Forms.CheckBox;$consent.Location=New-Object Drawing.Point(28,237);$consent.Size=New-Object Drawing.Size(445,55);$consent.Text='I understand this app sends device name, Windows version, agent version, online heartbeat, and a random installation ID to SolarNet.';$form.Controls.Add($consent)
$enroll=New-Object Windows.Forms.Button;$enroll.Text='Enroll this device';$enroll.Location=New-Object Drawing.Point(28,307);$enroll.Size=New-Object Drawing.Size(445,40);$enroll.BackColor=[Drawing.Color]::FromArgb(24,169,153);$enroll.FlatStyle='Flat';$form.Controls.Add($enroll)
$status=Label 'Status: Not enrolled' 28 369 445 28 $true;Label 'The application stays visible. No screen, file, keyboard, camera, microphone, or location data is collected.' 28 404 445 50|Out-Null
$timer=New-Object Windows.Forms.Timer;$timer.Interval=60000
$heartbeat={ $token=Read-Token;if(-not $token){$status.Text='Status: Not enrolled';return};try{Invoke-Api 'employee-device-agent/heartbeat' @{agent_version=$AgentVersion;os_version=[Environment]::OSVersion.VersionString} $token|Out-Null;$status.Text="Status: Online - heartbeat $(Get-Date -Format 'h:mm:ss tt')";$status.ForeColor=[Drawing.Color]::LightGreen}catch{$status.Text='Status: Server connection needs attention';$status.ForeColor=[Drawing.Color]::Orange}}
$timer.Add_Tick($heartbeat)
$enroll.Add_Click({if(-not $consent.Checked){[Windows.Forms.MessageBox]::Show('Review and accept the disclosed heartbeat data first.','Consent required')|Out-Null;return};if([string]::IsNullOrWhiteSpace($employee.Text)-or[string]::IsNullOrWhiteSpace($code.Text)){[Windows.Forms.MessageBox]::Show('Enter the employee name and one-time code.','Missing information')|Out-Null;return};$enroll.Enabled=$false;$status.Text='Status: Enrolling...';try{$r=Invoke-Api 'employee-device-agent/enroll' @{code=$code.Text.Trim();name=$env:COMPUTERNAME;employee_name=$employee.Text.Trim();platform='windows';os_version=[Environment]::OSVersion.VersionString;agent_version=$AgentVersion;device_fingerprint=(Get-Content $IdentityFile -Raw).Trim();consent_accepted=$true;consent_accepted_at=(Get-Date).ToUniversalTime().ToString('o')};Save-Token $r.data.device_token;$code.Clear();$employee.Enabled=$false;$consent.Enabled=$false;$enroll.Text='Enrolled';&$heartbeat;$timer.Start()}catch{$status.Text='Status: Enrollment failed';[Windows.Forms.MessageBox]::Show($_.Exception.Message,'Enrollment failed')|Out-Null;$enroll.Enabled=$true}})
if(Read-Token){$employee.Enabled=$false;$code.Enabled=$false;$consent.Checked=$true;$consent.Enabled=$false;$enroll.Text='Enrolled';$enroll.Enabled=$false;&$heartbeat;$timer.Start()}
[void]$form.ShowDialog()
