<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Models\StaffAttendanceRecord;
use App\Models\StaffLeaveRequest;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
class StaffLeaveController extends Controller {
 public function index(Request $request):JsonResponse{$year=(int)$request->input('year',now('Asia/Manila')->year);$manager=$request->user()->hasRole('super_admin');$q=StaffLeaveRequest::with(['user:id,name,email','reviewer:id,name'])->whereYear('start_date',$year);if(!$manager)$q->where('user_id',$request->user()->id);$rows=$q->latest()->get();$used=StaffLeaveRequest::where('user_id',$request->user()->id)->where('status','approved')->whereYear('start_date',$year)->sum('credit_days');return response()->json(['data'=>['year'=>$year,'annual_credits'=>10,'used_credits'=>(int)$used,'remaining_credits'=>max(0,10-(int)$used),'can_review'=>$manager,'requests'=>$rows]]);}
 public function store(Request $request):JsonResponse{abort_if($request->user()->hasRole('super_admin'),422,'Super Administrators are excluded from attendance, payroll, and employee leave credits.');$data=$request->validate(['start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','leave_type'=>['required',Rule::in(['personal','vacation','sick','emergency'])],'reason'=>'required|string|min:5|max:2000']);$start=Carbon::parse($data['start_date']);$end=Carbon::parse($data['end_date']);$days=$this->creditDays($start,$end);if($days<1)throw ValidationException::withMessages(['start_date'=>'The selected dates contain no working leave day.']);$year=$start->year;if($end->year!==$year)throw ValidationException::withMessages(['end_date'=>'A leave request cannot cross into another credit year.']);$committed=(int)StaffLeaveRequest::where('user_id',$request->user()->id)->whereIn('status',['pending','approved'])->whereYear('start_date',$year)->sum('credit_days');if($committed+$days>10)throw ValidationException::withMessages(['end_date'=>"Only ".max(0,10-$committed)." leave credit(s) remain for {$year}."]);$overlap=StaffLeaveRequest::where('user_id',$request->user()->id)->whereIn('status',['pending','approved'])->whereDate('start_date','<=',$end)->whereDate('end_date','>=',$start)->exists();if($overlap)throw ValidationException::withMessages(['start_date'=>'These dates overlap an existing pending or approved leave request.']);$leave=StaffLeaveRequest::create([...$data,'user_id'=>$request->user()->id,'credit_days'=>$days,'status'=>'pending']);return response()->json(['message'=>'Leave request submitted for approval.','data'=>$leave],201);}
 public function review(Request $request,StaffLeaveRequest $leave):JsonResponse{$data=$request->validate(['decision'=>['required',Rule::in(['approved','rejected'])],'review_notes'=>'nullable|string|max:2000']);abort_unless($request->user()->hasRole('super_admin'),403);if($leave->status!=='pending')throw ValidationException::withMessages(['decision'=>'Only a pending request can be reviewed.']);return DB::transaction(function()use($leave,$data,$request){if($data['decision']==='approved'){$used=(int)StaffLeaveRequest::where('id','!=',$leave->id)->where('user_id',$leave->user_id)->where('status','approved')->whereYear('start_date',$leave->start_date->year)->lockForUpdate()->sum('credit_days');if($used+$leave->credit_days>10)throw ValidationException::withMessages(['decision'=>'This approval would exceed the employee annual leave credits.']);$hasAttendance=StaffAttendanceRecord::where('user_id',$leave->user_id)->whereBetween('work_date',[$leave->start_date->toDateString(),$leave->end_date->toDateString()])->whereNotNull('clocked_in_at')->exists();if($hasAttendance)throw ValidationException::withMessages(['decision'=>'This employee already has a clock-in record within the requested leave dates. Correct the attendance record before approval.']);for($day=$leave->start_date->copy();$day->lte($leave->end_date);$day->addDay()){if($day->isSunday())continue;StaffAttendanceRecord::updateOrCreate(['user_id'=>$leave->user_id,'work_date'=>$day->toDateString()],['status'=>'leave','notes'=>'Approved '.$leave->leave_type.' leave: '.$leave->reason]);}}$leave->update(['status'=>$data['decision'],'reviewed_by'=>$request->user()->id,'reviewed_at'=>now(),'review_notes'=>$data['review_notes']??null]);return response()->json(['message'=>'Leave request '.$data['decision'].'.','data'=>$leave->fresh(['user','reviewer'])]);});}
 private function creditDays(Carbon $start,Carbon $end):int{$days=0;for($d=$start->copy();$d->lte($end);$d->addDay())if(!$d->isSunday())$days++;return $days;}
}
