import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Camera, CheckCircle2, Clock3, Download, LogIn, LogOut, RefreshCw, ShieldCheck } from 'lucide-react';
import api, { getErrorMessage } from '@/services/api';

interface BeforeInstallPromptEvent extends Event { prompt:()=>Promise<void>; userChoice:Promise<{outcome:'accepted'|'dismissed';platform:string}> }
declare global { interface Window { __solarnetInstallPrompt?: BeforeInstallPromptEvent; FaceDetector?: new (options?:{fastMode?:boolean;maxDetectedFaces?:number})=>{detect:(source:CanvasImageSource)=>Promise<unknown[]>} } }
type RecordRow={id:string;clocked_in_at:string|null;clocked_out_at:string|null};
type Employee={id:string;name:string;pin_configured:boolean;state:'not_clocked_in'|'clocked_in'|'clocked_out';record:RecordRow|null};
type Payload={server_time:string;timezone:string;employees:Employee[]};
const displayTime=(value?:string|null)=>value?new Date(value).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';

export default function AttendanceAppPage():React.JSX.Element{
  const videoRef=useRef<HTMLVideoElement|null>(null); const streamRef=useRef<MediaStream|null>(null);
  const [data,setData]=useState<Payload|null>(null); const [selectedId,setSelectedId]=useState(''); const [credential,setCredential]=useState(''); const [credentialType,setCredentialType]=useState<'pin'|'password'>('pin'); const [clock,setClock]=useState(Date.now()); const [busy,setBusy]=useState(false); const [cameraReady,setCameraReady]=useState(false); const [consent,setConsent]=useState(false); const [faceStatus,setFaceStatus]=useState('Camera not started'); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [prompt,setPrompt]=useState<BeforeInstallPromptEvent|null>(()=>window.__solarnetInstallPrompt||null);
  const selected=useMemo(()=>data?.employees.find(e=>e.id===selectedId)||null,[data,selectedId]);
  const load=useCallback(async()=>{try{const response=await api.get('/staff-attendance/kiosk');setData(response.data.data);setError('')}catch(e){setError(getErrorMessage(e))}},[]);
  useEffect(()=>{const manifest=document.querySelector<HTMLLinkElement>('link[rel="manifest"]');manifest?.setAttribute('href','/api/v1/attendance-app/manifest.webmanifest');const captured=()=>setPrompt(window.__solarnetInstallPrompt||null);window.addEventListener('solarnet:install-prompt-ready',captured);void load();const refresh=window.setInterval(()=>void load(),30000);const ticker=window.setInterval(()=>setClock(Date.now()),1000);return()=>{streamRef.current?.getTracks().forEach(track=>track.stop());window.removeEventListener('solarnet:install-prompt-ready',captured);window.clearInterval(refresh);window.clearInterval(ticker)}},[load]);
  const elapsed=useMemo(()=>{if(!selected?.record?.clocked_in_at)return'00:00:00';const start=new Date(selected.record.clocked_in_at).getTime();const end=selected.record.clocked_out_at?new Date(selected.record.clocked_out_at).getTime():clock;const seconds=Math.max(0,Math.floor((end-start)/1000));return[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(v=>String(v).padStart(2,'0')).join(':')},[clock,selected]);
  const startCamera=async()=>{setError('');try{streamRef.current?.getTracks().forEach(track=>track.stop());const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraReady(true);setFaceStatus('Position one face inside the guide')}catch(e){const denied=e instanceof DOMException&&(e.name==='NotAllowedError'||e.name==='SecurityError');setError(denied?'Camera permission is blocked. Open Android Settings → Apps → SolarNet Time (or Chrome) → Permissions → Camera → Allow, then fully close and reopen the Attendance app.':'No usable camera was detected. Check the device camera and try again.')}};
  const capture=async():Promise<{photo:Blob;faceCount:number}>=>{const video=videoRef.current;if(!video||!cameraReady||video.videoWidth<1)throw new Error('Start the camera and wait for the preview.');if(!window.FaceDetector)throw new Error('Face-presence detection is not supported by this browser. Update Chrome or use a supported kiosk device.');const detector=new window.FaceDetector({fastMode:true,maxDetectedFaces:2});const faces=await detector.detect(video);setFaceStatus(faces.length===1?'One face detected':faces.length===0?'No face detected':'Multiple faces detected');if(faces.length!==1)throw new Error(faces.length===0?'No face detected. Position your face inside the guide.':'Multiple faces detected. Only one employee may be visible.');const canvas=document.createElement('canvas');const max=720;const scale=Math.min(1,max/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d')?.drawImage(video,0,0,canvas.width,canvas.height);const photo=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Photo capture failed.')),'image/jpeg',0.82));return{photo,faceCount:faces.length}};
  const getLocation=()=>new Promise<GeolocationPosition|null>(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(resolve,()=>resolve(null),{enableHighAccuracy:true,timeout:8000,maximumAge:30000})});
  const punch=async(action:'clock_in'|'clock_out')=>{if(!selectedId||!credential){setError(`Select your employee name and enter your ${credentialType}.`);return}if(!consent){setError('Acknowledge the attendance photo notice before continuing.');return}setBusy(true);setError('');setMessage('');try{const {photo,faceCount}=await capture();const location=await getLocation();const form=new FormData();form.append('employee_id',selectedId);form.append('credential',credential);form.append('credential_type',credentialType);form.append('action',action);form.append('photo',photo,'attendance.jpg');form.append('photo_consent','1');form.append('face_count',String(faceCount));if(location){form.append('latitude',String(location.coords.latitude));form.append('longitude',String(location.coords.longitude))}const response=await api.post('/staff-attendance/kiosk/punch',form,{headers:{'Content-Type':'multipart/form-data'}});setMessage(`${response.data.message} ${selected?.name||''} · ${action==='clock_in'?'TIME IN':'TIME OUT'} · ${new Date().toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit'})}`);setCredential('');await load()}catch(e){setError(e instanceof Error&&!('response'in e)?e.message:getErrorMessage(e))}finally{setBusy(false)}};
  const install=async()=>{if(!prompt)return;await prompt.prompt();await prompt.userChoice;window.__solarnetInstallPrompt=undefined;setPrompt(null)};
  return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-sky-950 to-slate-950 p-4 text-white"><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-lg flex-col justify-center"><section className="overflow-hidden rounded-3xl border border-sky-300/20 bg-slate-950/80 shadow-2xl backdrop-blur"><header className="border-b border-white/10 bg-gradient-to-r from-sky-600/25 to-cyan-500/10 p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><img src="/solarnet-attendance-icon-192.png?v=20260914-attendance" alt="SolarNet Attendance" className="h-14 w-14 rounded-xl object-contain"/><div><h1 className="text-xl font-bold">SolarNet Time Kiosk</h1><p className="text-sm text-sky-100/75">Employee time in and time out</p></div></div><button onClick={()=>void load()} aria-label="Refresh" className="rounded-xl border border-white/15 p-2.5"><RefreshCw className="h-5 w-5"/></button></div></header><div className="space-y-5 p-6">
    <div className="text-center"><p className="text-sm font-medium text-sky-200">Philippine server time</p><p className="mt-1 font-mono text-3xl font-bold">{new Date(clock).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</p><p className="mt-1 text-xs text-slate-400">Employees must punch attendance on this authorized Super Administrator device.</p></div>
    <label className="block text-sm font-semibold text-slate-200">Employee<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setCredential('');setCredentialType('pin');setError('');setMessage('')}} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3 text-white"><option value="">Select your name</option>{(data?.employees||[]).map(e=><option key={e.id} value={e.id}>{e.name} · {e.state.replaceAll('_',' ')}</option>)}</select></label>
    {selected&&<div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-center"><div className="flex items-center justify-center gap-2 text-sky-200"><ShieldCheck className="h-5 w-5"/><span className="font-semibold">{selected.state==='clocked_in'?'Currently working':selected.state==='clocked_out'?'Shift completed':'Not clocked in'}</span></div><p className="mt-3 font-mono text-4xl font-bold">{elapsed}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-900/80 p-3"><p className="text-slate-400">Time in</p><p className="mt-1 font-semibold">{displayTime(selected.record?.clocked_in_at)}</p></div><div className="rounded-xl bg-slate-900/80 p-3"><p className="text-slate-400">Time out</p><p className="mt-1 font-semibold">{displayTime(selected.record?.clocked_out_at)}</p></div></div></div>}
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-black"><div className="relative aspect-square"><video ref={videoRef} muted playsInline className="h-full w-full scale-x-[-1] object-cover"/><div className="pointer-events-none absolute inset-[12%] rounded-[42%] border-2 border-dashed border-sky-300/80"/>{!cameraReady&&<button type="button" onClick={()=>void startCamera()} className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-slate-950/90 font-semibold text-sky-200"><Camera className="h-9 w-9"/>Start front camera</button>}</div><p className="px-3 py-2 text-center text-xs text-slate-300">{faceStatus}</p></div>
    <label className="flex items-start gap-3 rounded-xl border border-sky-300/20 bg-sky-500/10 p-3 text-xs leading-5 text-sky-100"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>Your camera will capture a photo when you record attendance. The photo is used as attendance evidence and may be reviewed by authorized administrators.</span></label>
    <div><div className="flex items-center justify-between gap-3"><label className="text-sm font-semibold text-slate-200">Employee {credentialType==='pin'?'PIN':'password'}</label><button type="button" onClick={()=>{setCredentialType(credentialType==='pin'?'password':'pin');setCredential('');setError('')}} className="text-xs font-semibold text-sky-300">Use {credentialType==='pin'?'password':'PIN'} instead</button></div><input type="password" inputMode={credentialType==='pin'?'numeric':undefined} pattern={credentialType==='pin'?'[0-9]*':undefined} maxLength={credentialType==='pin'?8:255} value={credential} onChange={e=>setCredential(credentialType==='pin'?e.target.value.replace(/\D/g,''):e.target.value)} autoComplete="off" placeholder={credentialType==='pin'?(selected?.pin_configured?'Enter your attendance PIN':'PIN not configured — use password'):'Enter your employee password'} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3 text-white"/></div>
    {error&&<p role="alert" className="rounded-xl border border-rose-400/30 bg-rose-500/10 p-3 text-sm text-rose-100">{error}</p>}{message&&<p className="flex items-center gap-2 rounded-xl border border-emerald-400/30 bg-emerald-500/10 p-3 text-sm text-emerald-100"><CheckCircle2 className="h-4 w-4"/>{message}</p>}
    <div className="grid grid-cols-2 gap-3"><button disabled={busy||selected?.state!=='not_clocked_in'} onClick={()=>void punch('clock_in')} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emerald-500 font-bold text-slate-950 disabled:opacity-35"><LogIn className="h-5 w-5"/>{busy?'Recording…':'Time in'}</button><button disabled={busy||selected?.state!=='clocked_in'} onClick={()=>void punch('clock_out')} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-amber-400 font-bold text-slate-950 disabled:opacity-35"><LogOut className="h-5 w-5"/>{busy?'Recording…':'Time out'}</button></div>
    {prompt&&<button onClick={()=>void install()} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-sky-300/30 px-4 py-3 font-semibold text-sky-100"><Download className="h-4 w-4"/>Install this kiosk</button>}<div className="border-t border-white/10 pt-4 text-xs text-slate-400"><span className="inline-flex items-center gap-1.5"><Clock3 className="h-4 w-4"/>Server-recorded punches · Employee password required</span></div>
  </div></section></div></main>
}
