import React, { useCallback, useEffect, useState } from 'react';
import { Download, Laptop, RefreshCw, ShieldCheck, Smartphone, UserCheck, XCircle } from 'lucide-react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { employeeDeviceService, type DeviceAudit, type EmployeeDevice } from '@/services/employeeDeviceService';

const EmployeeDeviceControllerPage: React.FC = () => {
  const [devices,setDevices]=useState<EmployeeDevice[]>([]); const [audits,setAudits]=useState<DeviceAudit[]>([]);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [enrollment,setEnrollment]=useState<{code:string;expires_at:string}|null>(null);
  const load=useCallback(async()=>{ try { setError(''); const data=await employeeDeviceService.index(); setDevices(data.devices); setAudits(data.audits); } catch { setError('Unable to load employee devices.'); } },[]);
  useEffect(()=>{ void load(); const timer=window.setInterval(()=>void load(),30000); return()=>window.clearInterval(timer); },[load]);
  const createCode=async()=>{ setBusy(true); try { setEnrollment(await employeeDeviceService.createEnrollment()); } catch { setError('Unable to create an enrollment code.'); } finally { setBusy(false); } };
  const revoke=async(device:EmployeeDevice)=>{ if(!window.confirm(`Revoke ${device.name}? Its agent will lose access immediately.`))return; setBusy(true); try{await employeeDeviceService.revoke(device.id);await load();}finally{setBusy(false);} };
  const online=devices.filter(d=>d.online).length; const pending=devices.filter(d=>d.status==='active'&&!d.online).length;
  return <DashboardLayout headerTitle="Employee Device Controller" headerSubtitle="Super Administrator secure device workspace"><div className="space-y-5">
    <section className="overflow-hidden rounded-3xl border border-blue-500/20 bg-gradient-to-br from-slate-950 via-blue-950 to-slate-950 p-6 text-white shadow-2xl shadow-blue-950/20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-cyan-300"><ShieldCheck className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[.2em]">Super Administrator only</span></div><h1 className="mt-3 text-3xl font-bold">SolarNet employee device control</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Optional enrollment and heartbeat monitoring for selected company devices. The portable Windows agent stays visible and collects only disclosed device status.</p></div><div className="flex flex-col gap-2"><button disabled={busy} onClick={createCode} className="rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 disabled:opacity-50">Create enrollment code</button><button disabled={busy} onClick={()=>void employeeDeviceService.downloadWindowsAgent()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 px-5 py-3 text-sm font-bold text-white"><Download className="h-4 w-4"/>Download Windows agent</button></div></div></section>
    {error&&<p className="rounded-xl border border-red-300 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">{error}</p>}
    {enrollment&&<section className="rounded-2xl border border-cyan-300 bg-cyan-50 p-5 dark:border-cyan-800 dark:bg-cyan-950/30"><p className="text-xs font-bold uppercase tracking-wider text-cyan-700 dark:text-cyan-300">One-time code</p><p className="mt-2 font-mono text-3xl font-black tracking-[.2em] text-foreground">{enrollment.code}</p><p className="mt-2 text-sm text-muted-foreground">Expires {new Date(enrollment.expires_at).toLocaleString()}. Enter it only in the signed SolarNet employee-device agent.</p></section>}
    <section className="grid gap-4 md:grid-cols-3">{[['Enrolled devices',devices.length,Laptop],['Online now',online,Smartphone],['Needs heartbeat',pending,UserCheck]].map(([label,value,Icon])=>{const I=Icon as typeof Laptop;return <article key={String(label)} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><I className="h-5 w-5 text-blue-500"/><p className="mt-5 text-sm text-muted-foreground">{String(label)}</p><p className="mt-1 text-3xl font-bold text-foreground">{String(value)}</p></article>})}</section>
    <section className="rounded-2xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-bold text-foreground">Enrolled company devices</h2><p className="text-sm text-muted-foreground">Online means a valid heartbeat was received within three minutes.</p></div><button onClick={()=>void load()} aria-label="Refresh devices"><RefreshCw className="h-5 w-5"/></button></div><div className="divide-y divide-border">{devices.length===0?<p className="p-10 text-center text-sm text-muted-foreground">No devices enrolled yet.</p>:devices.map(d=><article key={d.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex gap-3">{d.platform==='android'?<Smartphone/>:<Laptop/>}<div><p className="font-semibold text-foreground">{d.name}</p><p className="text-sm text-muted-foreground">{d.employee_name} · {d.platform} · {d.os_version||'OS not reported'} · agent {d.agent_version}</p><p className="mt-1 text-xs text-muted-foreground">Last heartbeat: {d.last_seen_at?new Date(d.last_seen_at).toLocaleString():'Never'}</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${d.online?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{d.status==='revoked'?'Revoked':d.online?'Online':'Offline'}</span>{d.status!=='revoked'&&<button disabled={busy} onClick={()=>void revoke(d)} className="inline-flex items-center gap-1 text-xs font-semibold text-red-600"><XCircle className="h-4 w-4"/>Revoke</button>}</div></article>)}</div></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="font-bold text-foreground">Security audit</h2><div className="mt-3 space-y-2">{audits.length===0?<p className="text-sm text-muted-foreground">No events recorded.</p>:audits.slice(0,12).map(a=><p key={a.id} className="rounded-lg bg-muted/50 p-3 text-sm text-foreground"><b>{a.event.replaceAll('_',' ')}</b><span className="ml-2 text-muted-foreground">{new Date(a.created_at).toLocaleString()}</span></p>)}</div></section>
  </div></DashboardLayout>;
};
export default EmployeeDeviceControllerPage;
