import { useCallback, useEffect, useState } from 'react';
import { CalendarClock, Camera, Clock3, Download, KeyRound, PhilippinePeso, Save, X } from 'lucide-react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import api, { getErrorMessage } from '@/services/api';

type Compensation = { monthly_salary:number; daily_rate:number; monthly_allowance:number; monthly_deduction:number; work_days_per_month:number; scheduled_start:string; scheduled_end:string; grace_minutes:number; overtime_multiplier:number };
type RecordRow = { id:string; work_date:string; clocked_in_at:string|null; clocked_out_at:string|null; status:string; late_minutes:number; worked_minutes:number; overtime_minutes:number; verification_method?:string|null; has_clock_in_photo?:boolean; has_clock_out_photo?:boolean; clock_in_photo_captured_at?:string|null; clock_out_photo_captured_at?:string|null; clock_in_device?:string|null; clock_out_device?:string|null; clock_in_ip_address?:string|null; clock_out_ip_address?:string|null };
type Employee = { id:string; name:string; email:string; roles:string[]; pin_configured:boolean; records:RecordRow[]; compensation:Compensation|null; summary:{present_days:number;late_days:number;late_minutes:number;worked_hours:number;overtime_hours:number;base_pay:number;overtime_pay:number;allowance:number;deductions:number;net_pay:number} };
type Payload = { month:string; can_manage_payroll:boolean; employees:Employee[] };
const money = (value:number):string => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(value||0);
const attendanceInstallerUrl = `${(import.meta.env.VITE_ATTENDANCE_URL || 'https://attendance.solarnetportal.com').replace(/\/$/, '')}/attendance-app/install`;

export default function StaffAttendancePage(): React.JSX.Element {
  const [month,setMonth]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'}).slice(0,7));
  const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState<Employee|null>(null); const [pinEmployee,setPinEmployee]=useState<Employee|null>(null); const [photoUrl,setPhotoUrl]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData((await api.get('/staff-attendance',{params:{month}})).data.data)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}},[month]);
  useEffect(()=>{void load()},[load]);
  return <DashboardLayout headerTitle="Attendance & Payroll" headerSubtitle="Server-clocked attendance and transparent salary computation"><main className="space-y-5">
    <section className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="flex items-center gap-2 text-xl font-bold text-foreground"><CalendarClock className="h-6 w-6 text-primary"/>Employee attendance</h1><p className="mt-1 text-sm text-muted-foreground">Clock times use the SolarNet server. Payroll is a reviewable computation until management approves payment. Super Administrators manage this workspace but are excluded from attendance and payroll.</p></div><div className="flex flex-wrap gap-2"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2 text-foreground"/><a href={attendanceInstallerUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-sky-600 px-4 py-2 font-semibold text-white hover:bg-sky-500"><Download className="h-4 w-4"/>Install Attendance App</a></div></div></section>
    {error&&<p role="alert" className="rounded-xl border border-rose-300 bg-rose-50 p-3 text-rose-800 dark:bg-rose-950/30 dark:text-rose-200">{error}</p>}
    <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/60 text-left text-muted-foreground"><tr><th className="p-3">Employee</th><th>Present</th><th>Late</th><th>Hours</th><th>Base</th><th>OT</th><th>Allowance</th><th>Deductions</th><th>Net pay</th><th>Action</th></tr></thead><tbody className="divide-y divide-border">{(data?.employees||[]).map(e=><tr key={e.id}><td className="p-3"><p className="font-semibold text-foreground">{e.name}</p><p className="text-xs text-muted-foreground">{e.roles.join(', ')} · PIN {e.pin_configured?'ready':'not set'}</p></td><td>{e.summary.present_days}</td><td>{e.summary.late_days} <span className="text-xs text-muted-foreground">({e.summary.late_minutes}m)</span></td><td>{e.summary.worked_hours}h</td><td>{money(e.summary.base_pay)}</td><td>{money(e.summary.overtime_pay)}</td><td>{money(e.summary.allowance)}</td><td>{money(e.summary.deductions)}</td><td className="font-bold text-emerald-700 dark:text-emerald-300">{money(e.summary.net_pay)}</td><td>{data?.can_manage_payroll&&<div className="flex flex-wrap gap-2"><button onClick={()=>setPinEmployee(e)} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 font-semibold text-foreground"><KeyRound className="h-4 w-4"/>{e.pin_configured?'Change PIN':'Set PIN'}</button><button onClick={()=>setEditing(e)} className="rounded-lg border border-border px-3 py-2 font-semibold text-foreground">Salary setup</button></div>}</td></tr>)}{!loading&&!data?.employees.length&&<tr><td colSpan={10} className="p-10 text-center text-muted-foreground">No employee records found.</td></tr>}</tbody></table></div></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-bold text-foreground"><Clock3 className="h-5 w-5"/>Daily details</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{(data?.employees||[]).map(e=><article key={e.id} className="rounded-xl border border-border p-4"><h3 className="font-semibold text-foreground">{e.name}</h3><div className="mt-2 max-h-72 overflow-auto">{e.records.map(r=><div key={r.id} className="border-t border-border py-2 text-xs"><div className="grid grid-cols-4 gap-2"><span>{r.work_date.slice(0,10)}</span><span>{r.clocked_in_at?new Date(r.clocked_in_at).toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}):'-'}</span><span>{r.clocked_out_at?new Date(r.clocked_out_at).toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}):'-'}</span><span className="capitalize">{r.status}</span></div>{r.verification_method==='camera_pin'&&<div className="mt-2 flex flex-wrap items-center gap-2"><span className="text-muted-foreground">PIN + live photo</span>{r.clock_in_photo_captured_at&&<button onClick={()=>void openPhoto(r.id,'clock-in')} className="inline-flex items-center gap-1 rounded border border-border px-2 py-1"><Camera className="h-3 w-3"/>Time-in photo</button>}{r.clock_out_photo_captured_at&&<button onClick={()=>void openPhoto(r.id,'clock-out')} className="inline-flex items-center gap-1 rounded border border-border px-2 py-1"><Camera className="h-3 w-3"/>Time-out photo</button>}</div>}</div>)}{!e.records.length&&<p className="text-xs text-muted-foreground">No attendance this month.</p>}</div></article>)}</div></section>
    {editing&&<CompensationModal employee={editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>}
    {pinEmployee&&<PinModal employee={pinEmployee} onClose={()=>setPinEmployee(null)} onSaved={async()=>{setPinEmployee(null);await load()}}/>}
    {photoUrl&&<div className="fixed inset-0 z-[190] grid place-items-center bg-black/80 p-4"><div className="relative max-h-[90vh] max-w-3xl"><img src={photoUrl} alt="Private attendance evidence" className="max-h-[88vh] rounded-2xl object-contain"/><button onClick={()=>{URL.revokeObjectURL(photoUrl);setPhotoUrl(null)}} className="absolute right-2 top-2 rounded-full bg-black/70 p-2 text-white"><X className="h-5 w-5"/></button></div></div>}
  </main></DashboardLayout>;

  async function openPhoto(recordId:string,type:'clock-in'|'clock-out'):Promise<void>{try{const response=await api.get(`/staff-attendance/records/${recordId}/photo/${type}`,{responseType:'blob'});if(photoUrl)URL.revokeObjectURL(photoUrl);setPhotoUrl(URL.createObjectURL(response.data))}catch(e){setError(getErrorMessage(e))}}
}

function PinModal({employee,onClose,onSaved}:{employee:Employee;onClose:()=>void;onSaved:()=>Promise<void>}):React.JSX.Element {
  const [pin,setPin]=useState(''); const [confirmation,setConfirmation]=useState(''); const [adminPassword,setAdminPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const save=async()=>{setBusy(true);setError('');try{await api.put(`/staff-attendance/${employee.id}/pin`,{pin,pin_confirmation:confirmation,admin_password:adminPassword});await onSaved()}catch(e){setError(getErrorMessage(e))}finally{setBusy(false)}};
  const pinInput=(value:string,setter:(value:string)=>void,placeholder:string)=><input type="password" inputMode="numeric" pattern="[0-9]*" maxLength={8} value={value} onChange={e=>setter(e.target.value.replace(/\D/g,''))} placeholder={placeholder} className="w-full rounded-lg border border-input bg-background px-3 py-2 text-foreground"/>;
  return <div className="fixed inset-0 z-[180] grid place-items-center bg-black/70 p-4"><section className="w-full max-w-md rounded-2xl bg-card p-5 shadow-2xl"><h2 className="flex items-center gap-2 text-lg font-bold text-foreground"><KeyRound className="h-5 w-5"/>Attendance PIN · {employee.name}</h2><p className="mt-2 text-sm text-muted-foreground">Assign a unique 4–8 digit PIN. Another employee's PIN will not authorize this employee's attendance.</p>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-4 space-y-3">{pinInput(pin,setPin,'New PIN')}{pinInput(confirmation,setConfirmation,'Confirm PIN')}<input type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} placeholder="Your Super Administrator password" autoComplete="current-password" className="w-full rounded-lg border border-input bg-background px-3 py-2 text-foreground"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border border-border px-4 py-2">Cancel</button><button disabled={busy||pin.length<4||pin!==confirmation||!adminPassword} onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground disabled:opacity-50"><Save className="h-4 w-4"/>{busy?'Saving…':'Save PIN'}</button></div></section></div>;
}

function CompensationModal({employee,onClose,onSaved}:{employee:Employee;onClose:()=>void;onSaved:()=>Promise<void>}):React.JSX.Element {
  const defaults:Compensation={monthly_salary:0,daily_rate:0,monthly_allowance:0,monthly_deduction:0,work_days_per_month:26,scheduled_start:'08:00',scheduled_end:'17:00',grace_minutes:15,overtime_multiplier:1.25};
  const [form,setForm]=useState<Compensation>({...defaults,...employee.compensation}); const [error,setError]=useState('');
  const field=(key:keyof Compensation,label:string,type='number')=><label className="text-sm text-foreground">{label}<input type={type} step={type==='number'?'0.01':undefined} value={form[key]} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2"/></label>;
  const save=async()=>{try{await api.put(`/staff-attendance/${employee.id}/compensation`,form);await onSaved()}catch(e){setError(getErrorMessage(e))}};
  return <div className="fixed inset-0 z-[180] grid place-items-center bg-black/70 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-card p-5 shadow-2xl"><h2 className="flex items-center gap-2 text-lg font-bold text-foreground"><PhilippinePeso className="h-5 w-5"/>Salary setup · {employee.name}</h2><p className="mt-1 text-xs text-muted-foreground">Base = effective daily rate × attended days. Net = base + overtime + allowance − late deduction − configured deductions.</p>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{field('monthly_salary','Monthly salary')}{field('daily_rate','Daily rate (used when set)')}{field('monthly_allowance','Monthly allowance')}{field('monthly_deduction','Other monthly deductions')}{field('work_days_per_month','Expected work days')}{field('grace_minutes','Late grace minutes')}{field('scheduled_start','Scheduled start','time')}{field('scheduled_end','Scheduled end','time')}{field('overtime_multiplier','Overtime multiplier')}</div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border border-border px-4 py-2">Cancel</button><button onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground"><Save className="h-4 w-4"/>Save</button></div></section></div>;
}
