import { useCallback, useEffect, useState } from 'react';
import { CalendarClock, Clock3, PhilippinePeso, Save } from 'lucide-react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import api, { getErrorMessage } from '@/services/api';

type Compensation = { monthly_salary:number; daily_rate:number; monthly_allowance:number; monthly_deduction:number; work_days_per_month:number; scheduled_start:string; scheduled_end:string; grace_minutes:number; overtime_multiplier:number };
type RecordRow = { id:string; work_date:string; clocked_in_at:string|null; clocked_out_at:string|null; status:string; late_minutes:number; worked_minutes:number; overtime_minutes:number };
type Employee = { id:string; name:string; email:string; roles:string[]; records:RecordRow[]; compensation:Compensation|null; summary:{present_days:number;late_days:number;late_minutes:number;worked_hours:number;overtime_hours:number;base_pay:number;overtime_pay:number;allowance:number;deductions:number;net_pay:number} };
type Payload = { month:string; can_manage_payroll:boolean; employees:Employee[] };
const money = (value:number):string => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(value||0);

export default function StaffAttendancePage(): React.JSX.Element {
  const [month,setMonth]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'}).slice(0,7));
  const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState<Employee|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData((await api.get('/staff-attendance',{params:{month}})).data.data)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}},[month]);
  useEffect(()=>{void load()},[load]);
  const act=async(action:'clock-in'|'clock-out')=>{try{await api.post(`/staff-attendance/${action}`);await load()}catch(e){setError(getErrorMessage(e))}};
  return <DashboardLayout headerTitle="Attendance & Payroll" headerSubtitle="Server-clocked attendance and transparent salary computation"><main className="space-y-5">
    <section className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="flex items-center gap-2 text-xl font-bold text-foreground"><CalendarClock className="h-6 w-6 text-primary"/>Employee attendance</h1><p className="mt-1 text-sm text-muted-foreground">Clock times use the SolarNet server. Payroll is a reviewable computation until management approves payment.</p></div><div className="flex flex-wrap gap-2"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2 text-foreground"/><button onClick={()=>void act('clock-in')} className="rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white">Clock in</button><button onClick={()=>void act('clock-out')} className="rounded-lg bg-slate-700 px-4 py-2 font-semibold text-white">Clock out</button></div></div></section>
    {error&&<p role="alert" className="rounded-xl border border-rose-300 bg-rose-50 p-3 text-rose-800 dark:bg-rose-950/30 dark:text-rose-200">{error}</p>}
    <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/60 text-left text-muted-foreground"><tr><th className="p-3">Employee</th><th>Present</th><th>Late</th><th>Hours</th><th>Base</th><th>OT</th><th>Allowance</th><th>Deductions</th><th>Net pay</th><th>Action</th></tr></thead><tbody className="divide-y divide-border">{(data?.employees||[]).map(e=><tr key={e.id}><td className="p-3"><p className="font-semibold text-foreground">{e.name}</p><p className="text-xs text-muted-foreground">{e.roles.join(', ')}</p></td><td>{e.summary.present_days}</td><td>{e.summary.late_days} <span className="text-xs text-muted-foreground">({e.summary.late_minutes}m)</span></td><td>{e.summary.worked_hours}h</td><td>{money(e.summary.base_pay)}</td><td>{money(e.summary.overtime_pay)}</td><td>{money(e.summary.allowance)}</td><td>{money(e.summary.deductions)}</td><td className="font-bold text-emerald-700 dark:text-emerald-300">{money(e.summary.net_pay)}</td><td>{data?.can_manage_payroll&&<button onClick={()=>setEditing(e)} className="rounded-lg border border-border px-3 py-2 font-semibold text-foreground">Salary setup</button>}</td></tr>)}{!loading&&!data?.employees.length&&<tr><td colSpan={10} className="p-10 text-center text-muted-foreground">No employee records found.</td></tr>}</tbody></table></div></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-bold text-foreground"><Clock3 className="h-5 w-5"/>Daily details</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{(data?.employees||[]).map(e=><article key={e.id} className="rounded-xl border border-border p-4"><h3 className="font-semibold text-foreground">{e.name}</h3><div className="mt-2 max-h-64 overflow-auto">{e.records.map(r=><div key={r.id} className="grid grid-cols-4 gap-2 border-t border-border py-2 text-xs"><span>{r.work_date.slice(0,10)}</span><span>{r.clocked_in_at?new Date(r.clocked_in_at).toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}):'-'}</span><span>{r.clocked_out_at?new Date(r.clocked_out_at).toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}):'-'}</span><span className="capitalize">{r.status}</span></div>)}{!e.records.length&&<p className="text-xs text-muted-foreground">No attendance this month.</p>}</div></article>)}</div></section>
    {editing&&<CompensationModal employee={editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>}
  </main></DashboardLayout>;
}

function CompensationModal({employee,onClose,onSaved}:{employee:Employee;onClose:()=>void;onSaved:()=>Promise<void>}):React.JSX.Element {
  const defaults:Compensation={monthly_salary:0,daily_rate:0,monthly_allowance:0,monthly_deduction:0,work_days_per_month:26,scheduled_start:'08:00',scheduled_end:'17:00',grace_minutes:15,overtime_multiplier:1.25};
  const [form,setForm]=useState<Compensation>({...defaults,...employee.compensation}); const [error,setError]=useState('');
  const field=(key:keyof Compensation,label:string,type='number')=><label className="text-sm text-foreground">{label}<input type={type} step={type==='number'?'0.01':undefined} value={form[key]} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2"/></label>;
  const save=async()=>{try{await api.put(`/staff-attendance/${employee.id}/compensation`,form);await onSaved()}catch(e){setError(getErrorMessage(e))}};
  return <div className="fixed inset-0 z-[180] grid place-items-center bg-black/70 p-4"><section className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-card p-5 shadow-2xl"><h2 className="flex items-center gap-2 text-lg font-bold text-foreground"><PhilippinePeso className="h-5 w-5"/>Salary setup · {employee.name}</h2><p className="mt-1 text-xs text-muted-foreground">Base = effective daily rate × attended days. Net = base + overtime + allowance − late deduction − configured deductions.</p>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{field('monthly_salary','Monthly salary')}{field('daily_rate','Daily rate (used when set)')}{field('monthly_allowance','Monthly allowance')}{field('monthly_deduction','Other monthly deductions')}{field('work_days_per_month','Expected work days')}{field('grace_minutes','Late grace minutes')}{field('scheduled_start','Scheduled start','time')}{field('scheduled_end','Scheduled end','time')}{field('overtime_multiplier','Overtime multiplier')}</div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border border-border px-4 py-2">Cancel</button><button onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground"><Save className="h-4 w-4"/>Save</button></div></section></div>;
}
