import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ClipboardList, MapPin, Navigation, Search, UserPlus } from 'lucide-react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import api from '@/services/api';

type Client = { id: string; account_number: string; full_name: string; address?: string; status: string; gps_coordinates: { latitude: number; longitude: number } };
type Ticket = { id: string; ticket_number: string; subject: string; description: string; status: string; priority: string; customer?: Client };

export default function TechnicianDashboardPage() {
  const [tab, setTab] = useState<'map' | 'tickets' | 'application'>('map');
  const [clients, setClients] = useState<Client[]>([]);
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [selected, setSelected] = useState<Client | null>(null);
  const [query, setQuery] = useState('');
  const [error, setError] = useState('');

  useEffect(() => { void api.get('/dashboard/technician').then((response) => { setClients(response.data.clients || []); setTickets(response.data.tickets || []); setSelected(response.data.clients?.[0] || null); }).catch((e) => setError(e.response?.data?.message || 'Could not load assigned field work.')); }, []);
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return term ? clients.filter((client) => `${client.full_name} ${client.account_number} ${client.address || ''}`.toLowerCase().includes(term)) : clients; }, [clients, query]);
  const mapUrl = selected ? `https://www.google.com/maps?q=${selected.gps_coordinates.latitude},${selected.gps_coordinates.longitude}&output=embed` : '';
  const directions = selected ? `https://www.google.com/maps/dir/?api=1&destination=${selected.gps_coordinates.latitude},${selected.gps_coordinates.longitude}` : '#';

  return <DashboardLayout><main className="mx-auto max-w-7xl space-y-5 p-4 md:p-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Field workspace</p><h1 className="mt-1 text-2xl font-bold">Technician dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Assigned locations, tickets, and client applications.</p></header>
    <div className="flex gap-2 border-b"><button onClick={() => setTab('map')} className={`px-4 py-2 text-sm font-semibold ${tab === 'map' ? 'border-b-2 border-primary text-primary' : 'text-muted-foreground'}`}><MapPin className="mr-1 inline h-4 w-4" />Client map</button><button onClick={() => setTab('tickets')} className={`px-4 py-2 text-sm font-semibold ${tab === 'tickets' ? 'border-b-2 border-primary text-primary' : 'text-muted-foreground'}`}><ClipboardList className="mr-1 inline h-4 w-4" />My tickets</button><button onClick={() => setTab('application')} className={`px-4 py-2 text-sm font-semibold ${tab === 'application' ? 'border-b-2 border-primary text-primary' : 'text-muted-foreground'}`}><UserPlus className="mr-1 inline h-4 w-4" />New client application</button></div>
    {error && <p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    {tab === 'map' && <section className="grid gap-5 lg:grid-cols-[340px_1fr]"><article className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Client location map</h2><p className="mt-1 text-xs text-muted-foreground">Search a client, select their pin, then open Google Maps for directions.</p><div className="relative mt-4"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search client name or account" className="w-full rounded-lg border bg-background py-2 pl-9 pr-3 text-sm" /></div></div><div className="max-h-[540px] overflow-y-auto">{visible.map((client) => <button key={client.id} onClick={() => setSelected(client)} className={`w-full border-b p-4 text-left hover:bg-muted/50 ${selected?.id === client.id ? 'bg-primary/5' : ''}`}><p className="font-semibold">{client.full_name}</p><p className="text-xs text-muted-foreground">{client.account_number} · {client.address || 'To be updated'}</p><span className="mt-2 inline-flex rounded-full bg-muted px-2 py-1 text-[11px] font-semibold capitalize">{client.status}</span></button>)}{!visible.length && <p className="p-5 text-sm text-muted-foreground">No assigned clients found.</p>}</div></article><article className="overflow-hidden rounded-2xl border bg-card">{selected ? <><iframe title={`Google map for ${selected.full_name}`} src={mapUrl} className="h-[440px] w-full border-0" loading="lazy" /><div className="flex items-center justify-between gap-3 p-4"><div><p className="font-semibold">Selected: {selected.full_name}</p><p className="text-sm text-muted-foreground">{selected.gps_coordinates.latitude}, {selected.gps_coordinates.longitude}</p></div><a href={directions} target="_blank" rel="noreferrer" className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><Navigation className="mr-1 inline h-4 w-4" />Open Google Maps</a></div></> : <p className="p-8 text-sm text-muted-foreground">Select a client to open their Google Map location.</p>}</article></section>}
    {tab === 'tickets' && <section className="space-y-3">{tickets.map((ticket) => <article key={ticket.id} className="rounded-2xl border bg-card p-5"><p className="text-xs font-semibold text-primary">{ticket.ticket_number}</p><h2 className="mt-1 font-semibold">{ticket.subject}</h2><p className="mt-2 text-sm text-muted-foreground">{ticket.description}</p><p className="mt-3 text-sm">{ticket.customer?.full_name || 'Unassigned client'} · {ticket.customer?.address || 'No address'} · <span className="capitalize">{ticket.priority} / {ticket.status}</span></p></article>)}{!tickets.length && <p className="rounded-2xl border bg-card p-8 text-center text-sm text-muted-foreground">No open tickets assigned to you.</p>}</section>}
    {tab === 'application' && <section className="rounded-2xl border bg-card p-6"><UserPlus className="h-8 w-8 text-primary" /><h2 className="mt-3 text-lg font-semibold">New client application</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">Record a prospective client’s details and exact installation location. The application remains pending for office approval.</p><Link to="/signup" className="mt-5 inline-flex rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Start new application</Link></section>}
  </main></DashboardLayout>;
}
